using CodeFactory.Automation.Standard.Logic.Extensions;
using CodeFactory.WinVs;
using CodeFactory.WinVs.Models.CSharp;
using CodeFactory.WinVs.Models.ProjectSystem;
using System.Threading.Tasks;

namespace CodeFactory.Automation.NDF.Logic.Node.Angular
{
	/// <summary>
	/// Automation logic for creating and updated a local service within an angular project.
	/// </summary>
	public static class LocalServiceBuilder
    {
        public static async Task<VsDocument> RefreshAngularService(this IVsActions source, CsClass controllerClass,
            VsProject angularWebProject, VsProjectFolder modulesFolder = null, VsProjectFolder modelsFolder = null, VsProjectFolder servicesFolder = null)
        {
            if (source == null)
                throw new CodeFactoryException("CodeFactory automation was not provided cannot refresh the angular service.");

            if (controllerClass == null)
                throw new CodeFactoryException("Cannot load the controller class, cannot refresh the angular service.");

            if (angularWebProject == null)
                throw new CodeFactoryException("Cannot load the angular web project, cannot refresh the angular service.");

            // Build controller name
            var controllerName = $"{controllerClass.Name.GenerateCSharpFormattedClassName().ToLower()}";

            // Strip the suffix
            var strippedName = controllerName.Replace("controller", "").GenerateCSharpProperCase();

            // Get or create the service
            var serviceFileName = $"{modulesFolder.Name}-{strippedName.ToLower()}-api.service";
            var serviceClassName = $"{modulesFolder.Name}{strippedName}ApiService";
            VsDocument serviceDocument = (await servicesFolder.FindTypscriptSourceByClassNameAsync(serviceClassName))
                                     ?? await source.CreateAngularServiceAsync(controllerClass, angularWebProject, serviceFileName, serviceClassName, modulesFolder, modelsFolder, servicesFolder);
            
            return serviceDocument;
        }

        private static async Task<VsDocument> CreateAngularServiceAsync(this IVsActions source, CsClass controllerClass,
            VsProject angularWebProject, string serviceFileName, string serviceClassName, VsProjectFolder modulesFolder = null, VsProjectFolder modelsFolder = null, VsProjectFolder servicesFolder = null)
        {
            if (source == null)
                throw new CodeFactoryException("CodeFactory automation was not provided cannot refresh the angular service.");

            if (controllerClass == null)
                throw new CodeFactoryException("Cannot load the controller class, cannot refresh the angular service.");

            if (angularWebProject == null)
                throw new CodeFactoryException("Cannot load the angular web project, cannot refresh the angular service.");

            var test = controllerClass.Methods[0].MethodType;
            var sourceFormatter = new SourceFormatter();
			sourceFormatter.AppendCodeLine(0, $"/* Autogenerated Angular Service */");
			sourceFormatter.AppendCodeLine(0, "import { Injectable } from \"@angular/core\";");
            sourceFormatter.AppendCodeLine(0, "import { HttpClient } from '@angular/common/http';");
            sourceFormatter.AppendCodeLine(0, "import { Observable, map } from \"rxjs\";");

			foreach (var method in controllerClass.Methods)
			{
				if (method.HasParameters)
				{
					foreach (var parameter in method.Parameters)
					{
						if (parameter.Name.ToLower().EndsWith("model") && !parameter.ParameterType.IsWellKnownType)
						{
							// Resolve the cs class model
							var csClassModel = parameter.ParameterType.GetClassModel();

							// Get the stripped Name
							var strippedClassName = csClassModel.Name.Replace("Model", "").GenerateCSharpProperCase();

							// Get or create the model
							var modelClassName = $"{strippedClassName.ToKebabCase()}";
							var modelFileName = $"{modulesFolder.Name}-{modelClassName}.model";
                            var importStatement = "import { " + strippedClassName + " }";

                            // Import the model reference if it hasn't already been imported
							if (!sourceFormatter.ReturnSource().Contains(importStatement))
							    sourceFormatter.AppendCodeLine(0, importStatement + " from '../" + modelsFolder.Name + "/" + modelFileName + "';");
						}
					}
				}
			}			
            
            sourceFormatter.AppendCodeLine(0);
            sourceFormatter.AppendCodeLine(0, "@Injectable({ providedIn: 'root' })");
            sourceFormatter.AppendCodeLine(0, "export class " + serviceClassName + " {");

			// Add Constructor
			sourceFormatter.AppendCodeLine(1, $"/* Constructor */");
			sourceFormatter.AppendCodeLine(1, "constructor(private http: HttpClient) {");
            sourceFormatter.AppendCodeLine(1, "}");
            sourceFormatter.AppendCodeLine(0);

			// Add Methods based-on the Controller in the BFF
			foreach (var method in controllerClass.Methods)
			{
                // Skip if the method is not public
                if (method.Security == CsSecurity.Public)
                {
                    sourceFormatter.AppendCodeLine(0, $"/* Method to {method.Name.Prettify()} */");

                    // Get the action type
                    var action = "get";
                    // TODO Uncomment when ready to support posts
                    //if (method.HasAttributes && method.Attributes.Any(a => a.Type.Name == "HttpPostAttribute"))
                    //{
                    //    action = "post";
                    //}

					// Get the Return Type
					var returnType = "";
					if (method.ReturnType.HasStrongTypesInGenerics)
					{
						returnType = method.ReturnType.GenericTypes[0].Name;
						if (returnType.EndsWith("Model"))
							returnType = returnType.Replace("Model", "");
					}
					else
					{
						returnType = method.ReturnType.Name;
					}

					// Build Signature
					var signatureParameters = "";
					if (method.HasParameters)
                    {
                        // Build parameters                        
                        for (int i = 0; i < method.Parameters.Count; i++)
                        {
                            if(i > 0)
								signatureParameters += ", ";

							signatureParameters += $"{method.Parameters[i].Name}: {TypescriptConverter.ConvertToTypeScriptType(method.Parameters[i].ParameterType.Name)}";
                        }						
					}
					sourceFormatter.AppendCodeLine(0, $"{method.Name.GenerateCSharpCamelCase()}({signatureParameters}): Observable<{TypescriptConverter.ConvertToTypeScriptType(returnType)}>");

					// Add thie method body
                    sourceFormatter.AppendCodeLine(0, "{");
                    var urlParameters = "";
                    if (method.HasParameters)
                    {
                        // Build parameters                        
                        for (int i = 0; i < method.Parameters.Count; i++)
                        {
                            if (i > 0)
								urlParameters += "&";
                            else
								urlParameters += "?";

							urlParameters += "{" + method.Parameters[i].Name + "}";
                        }
                    }
                    sourceFormatter.AppendCodeLine(1, "return this.http."+ action +"(`/api/v1/t1/"+ method.Name.ToLower() + "/$"+ urlParameters + "`).pipe(map(r => r as "+ returnType +"));");
                    sourceFormatter.AppendCodeLine(0, "}");
                }
			}

			sourceFormatter.AppendCodeLine(0, "}");

            // Add the document
            var sourceDocument = (await servicesFolder.AddDocumentAsync($"{serviceFileName}.ts", sourceFormatter.ReturnSource().TrimStartEndLines()))
                ?? throw new CodeFactoryException($"Was not able to load the created angular service implementation for '{serviceFileName}.ts'");

            return sourceDocument;
        }        
    }
}