using CodeFactory.Automation.Standard.Logic.Extensions;
using CodeFactory.WinVs.Models.CSharp;

namespace CodeFactory.Automation.NDF.Logic.Node.Angular
{
	/// <summary>
	/// Automation library that creates a model class that supports standard node angular implementation.
	/// </summary>
	public static class TypescriptConverter
    {
        // <summary>
        // Converts a C# class model to an Angular model class in TypeScript.
        //
        // Parameters:
        // - csharpModel: The C# class model to be converted.
        //
        // Returns:
        // - A string representing the TypeScript model class.
        // </summary>
        public static string ConvertCsModeltoTs(CsClass csharpModel, string targetModelName)
        {
            // Create a StringBuilder to store the TypeScript model class.
            var sourceFormatter = new SourceFormatter();
            sourceFormatter.AppendCodeLine(0, $"/* Autogenerated model file */");
            sourceFormatter.AppendCodeLine(0, $"export class {targetModelName}");
            sourceFormatter.AppendCodeLine(0, "{");

            // Iterate through each property of the C# model.
            foreach (var property in csharpModel.Properties)
            {
                // Convert the C# property type to TypeScript.
                string tsType = ConvertToTypeScriptType(property.PropertyType.Name);

                // Append the TypeScript property to the model class.
                sourceFormatter.AppendCodeLine(2, $"{property.Name}?: {tsType};");
            }

            // Add the default model.
            sourceFormatter.AppendCodeLine(0);
            sourceFormatter.AppendCodeLine(1, "static default() {");
            sourceFormatter.AppendCodeLine(2, $"const def = new {targetModelName}();");
            foreach (var property in csharpModel.Properties)
            {
                sourceFormatter.AppendCodeLine(2, $"def.{property.Name} = {GetDefaultValueFromTypeScriptType(property.PropertyType.Name)};");
            }

            sourceFormatter.AppendCodeLine(1, "}");
            sourceFormatter.AppendCodeLine(0, "}");

            // Return the TypeScript model class.
            return sourceFormatter.ReturnSource().TrimStartEndLines();
        }

        // <summary>
        // Converts a C# property type to the equivalent TypeScript type.
        //
        // Parameters:
        // - csharpType: The C# property type to be converted.
        //
        // Returns:
        // - A string representing the equivalent TypeScript type. 
        // </summary>
        public static string ConvertToTypeScriptType(string csharpType)
        {
            switch (csharpType.ToLower())
            {
                case "int":
                case "int32":
                case "int64":
                case "long":
                case "float":
                case "decimal":
                case "double":
                    return "number";
                case "task":
                case "list":
                case "collection":
                case "ienumeration":
                    return "any";
                case "boolean":
                    return "boolean";
                case "string":
                    return "string";
                case "datetime":
                    return "Date";
                default:
                    return csharpType;
            }
        }

        // <summary>
        // Gets a C# property type, Typescript equivelant, default value.
        //
        // Parameters:
        // - csharpType: The C# property type.
        //
        // Returns:
        // - A string representing the equivalent TypeScript type default value.
        // </summary>
        public static string GetDefaultValueFromTypeScriptType(string csharpType)
        {
            switch (csharpType.ToLower())
            {
                case "int":
                case "int32":
                case "int64":
                case "long":
                case "float":
                case "decimal":
                case "double":
                    return "0";
                case "task":
                case "list":
                case "collection":
                case "ienumerable":
                    return "{}";
                case "boolean":
                    return "false";
                case "string":
                    return "\"\"";
                case "datetime":
                    return "new Date()";
                default:
                    return "null";
            }
        }        
    }
}